// generated by Fast Light User Interface Designer (fluid) version 1.0306

#ifndef interface_h
#define interface_h
#include <FL/Fl.H>
// To use FLTK add this to the linker: -lfltk -luuid -lcomctl32 -lgdi32
#include <iostream>
#include <vector>
#include <string>
#include <FL/Fl_Native_File_Chooser.H>
/**
 Needed for the prompt to save or not
*/
#include <FL/fl_ask.H>
/**
 Loading Embedded Images
*/
#include <FL/Fl_Image.H>
/**
 Allows Images In Menu
*/
#include <FL/Fl_Multi_Label.H>
/**
 To Load Text into the Text Display Control
*/
#include <FL/FL_Text_Display.H>
/**
 Load Custom Tree
*/
#include <FL/Fl_Tree.H>
/**
 Needed to Load Icon
*/
#include <FL/x.H>
#include <windows.h>
#include <dwmapi.h> // need to link -ldwmapi
#include "scriptini.h" // class to read and write ini files
#include "appsettings.h" // Holds Common Settings / Variables
#include "stringenc.h" // converting between unicode and UTF8
extern Fl_Text_Buffer *tree_text; 
extern Fl_Text_Buffer *credits; 
extern Fl_Text_Buffer *license_notices; 
void toggle_theme();
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_settings;
#include <FL/Fl_Button.H>
#include <FL/Fl_Input.H>
extern Fl_Input *edt_game_path;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *chk_darkmode;
extern Fl_Double_Window *win_about;
extern Fl_Button *btn_about_close;
#include <FL/Fl_Box.H>
#include <FL/Fl_Text_Display.H>
void btn_open_pressed();

class MyTree : public Fl_Tree {
  static void Copy_CB(Fl_Widget*, void *userdata);
  static void Paste_CB(Fl_Widget*, void *userdata);
public:
  int handle(int e);
  ~MyTree();
  MyTree(int width, int height, int xlim, int ylim) ;
};
void re4_util_ui_close();
extern Fl_Double_Window *ui_main;
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Progress.H>
extern MyTree *tree;
extern Fl_Button *btn_open;
extern Fl_Input *edt_file;
Fl_Double_Window* re4_util_ui();
extern Fl_Menu_Item menu_[];
#define dm_file (menu_+0)
#define mi_new (menu_+1)
#define mi_open (menu_+2)
#define mi_save (menu_+3)
#define mi_saveas (menu_+4)
#define mi_settings (menu_+5)
#define mi_exit (menu_+6)
#define dm_edit (menu_+8)
#define mi_import (menu_+9)
#define mi_export (menu_+10)
#define mi_replace (menu_+11)
#define dm_help (menu_+13)
#define mi_help (menu_+14)
#define mi_about (menu_+15)
#endif
