// link: fltk, uuid, comctl32, gdi32
// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef win_esl_h
#define win_esl_h
#include <FL/Fl.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Ask.H>
/**
 the esl cannot excced 256 entries because it gets copied into the game save
*/
#define MAX_ROWS 256
#define MAX_COLS 16
#include <FL/x.H> // Needed to Load Icon
#include <FL/Fl_Menu_.H>
#include <FL/Fl_Table.H>
#include <FL/Fl_Int_Input.H>
#include <iostream>
#include <FL/Fl_Draw.H>
#include "resource.h"
void callback_mnu_open();
void callback_mnu_save();
void callback_mnu_csv_exp();
void callback_mnu_csv_imp();
void callback_mnu_exit();

class MyTable : public Fl_Table {
  Fl_Int_Input *input; // single instance of Fl_Int_Input widget
  int data[MAX_ROWS][MAX_COLS]; // data array for cells
  int row_edit, col_edit; // row/col being modified
  int s_left, s_top, s_right, s_bottom; // kb nav + mouse selection
  int _sort_reverse, _sort_lastcol;
protected:
  void draw_cell(TableContext context, int R,int C, int X,int Y,int W,int H);
  void event_callback2();
  static void event_callback(Fl_Widget*,void *v);
  static void input_cb(Fl_Widget*,void* v);
  void draw_sort_arrow(int X,int Y,int W,int H);
public:
  MyTable(int X, int Y, int W, int H, const char *L=0) ;
  void set_value_hide();
  void rows(int val);
  void cols(int val);
  inline int rows();
  inline int cols();
  void start_editing(int R, int C);
  void done_editing();
};
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
Fl_Double_Window* win_esl();
extern Fl_Menu_Item menu_MENU[];
#endif
